// This line imports the pre-caching logic generated by vite-plugin-pwa/workbox
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// `self.__WB_MANIFEST` is injected by the vite-plugin-pwa.
// It contains a list of all assets to precache.
precacheAndRoute(self.__WB_MANIFEST);

// Add custom event listeners or caching strategies here, e.g.:

// self.addEventListener('fetch', (event) => {
//   // Custom caching strategy for a specific API endpoint
//   if (event.request.url.includes('/api/data')) {
//     // ...
//   }
// });
